feat: few changes in docker-compose.yml

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -2,10 +2,7 @@ version: "3"
 
 services:
   backend:
-    build:
-      context: .
-    env_file:
-      - .env
+    image: geniusdynamics/custom-erpnext:v1.0.0
     deploy:
       restart_policy:
         condition: on-failure
@@ -13,10 +10,71 @@ services:
       - sites:/home/frappe/frappe-bench/sites
       - logs:/home/frappe/frappe-bench/logs
 
+  configurator:
+    image: geniusdynamics/custom-erpnext:v1.0.0
+    deploy:
+      restart_policy:
+        condition: none
+    entrypoint:
+      - bash
+      - -c
+    # add redis_socketio for backward compatibility
+    command:
+      - >
+        ls -1 apps > sites/apps.txt;
+        bench set-config -g db_host $$DB_HOST;
+        bench set-config -gp db_port $$DB_PORT;
+        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
+        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
+        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
+        bench set-config -gp socketio_port $$SOCKETIO_PORT;
+    environment:
+      DB_HOST: db
+      DB_PORT: "3306"
+      REDIS_CACHE: redis-cache:6379
+      REDIS_QUEUE: redis-queue:6379
+      SOCKETIO_PORT: "9000"
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  create-site:
+    image: geniusdynamics/custom-erpnext:v1.0.0
+    deploy:
+      restart_policy:
+        condition: none
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+    entrypoint:
+      - bash
+      - -c
+    command:
+      - >
+        wait-for-it -t 120 db:3306;
+        wait-for-it -t 120 redis-cache:6379;
+        wait-for-it -t 120 redis-queue:6379;
+        export start=`date +%s`;
+        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+        do
+          echo "Waiting for sites/common_site_config.json to be created";
+          sleep 5;
+          if (( `date +%s`-start > 120 )); then
+            echo "could not find sites/common_site_config.json with required keys";
+            exit 1
+          fi
+        done;
+        echo "sites/common_site_config.json found";
+        bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=admin --install-app erpnext --set-default frontend;
+
   db:
     image: mariadb:10.6
-    env_file:
-      - .env
+    healthcheck:
+      test: mysqladmin ping -h localhost --password=admin
+      interval: 1s
+      retries: 15
     deploy:
       restart_policy:
         condition: on-failure
@@ -25,16 +83,15 @@ services:
       - --collation-server=utf8mb4_unicode_ci
       - --skip-character-set-client-handshake
       - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
+    environment:
+      MYSQL_ROOT_PASSWORD: admin
     volumes:
       - db-data:/var/lib/mysql
 
   frontend:
-    build:
-      context: .
+    image: geniusdynamics/custom-erpnext:v1.0.0
     depends_on:
       - websocket
-    env_file:
-      - .env
     deploy:
       restart_policy:
         condition: on-failure
@@ -43,7 +100,7 @@ services:
     environment:
       BACKEND: backend:8000
       FRAPPE_SITE_NAME_HEADER: frontend
-      SOCKETIO: websocket:${SOCKETIO_PORT}
+      SOCKETIO: websocket:9000
       UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
       UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
       UPSTREAM_REAL_IP_RECURSIVE: "off"
@@ -56,10 +113,7 @@ services:
       - "8080:8080"
 
   queue-long:
-    build:
-      context: .
-    env_file:
-      - .env
+    image: geniusdynamics/custom-erpnext:v1.0.0
     deploy:
       restart_policy:
         condition: on-failure
@@ -73,10 +127,7 @@ services:
       - logs:/home/frappe/frappe-bench/logs
 
   queue-short:
-    build:
-      context: .
-    env_file:
-      - .env
+    image: geniusdynamics/custom-erpnext:v1.0.0
     deploy:
       restart_policy:
         condition: on-failure
@@ -106,10 +157,7 @@ services:
       - redis-cache-data:/data
 
   scheduler:
-    build:
-      context: .
-    env_file:
-      - .env
+    image: geniusdynamics/custom-erpnext:v1.0.0
     deploy:
       restart_policy:
         condition: on-failure
@@ -121,10 +169,7 @@ services:
       - logs:/home/frappe/frappe-bench/logs
 
   websocket:
-    build:
-      context: .
-    env_file:
-      - .env
+    image: geniusdynamics/custom-erpnext:v1.0.0
     deploy:
       restart_policy:
         condition: on-failure
